### ISSUE TITLE
[ADD] Comments on JOSS paper

### ISSUE THREAD

**Issue by tmigot** [artefactory/choice-learn#146]
## 🚀 Feature Request

Suggestions regarding JOSS paper :
- [x] p.3 L.45: I think it should be made clearer that the `FeaturesStorage` structure comes from this packages and not numpy
- [x] p.3 L.51: L-BFGS is not a second-order algorithm as it doesn't use any second-order information on the problem. It is true though that it uses first-order information to build an approximation of the second-order.
- [x] The paper is quite long for JOSS format, and it would be great (also optional IMO), one suggestion would be to remove the *Streamlined signature* section. In general, the paper should focus on the main points.
## 📎 Additional context

Connected to https://github.com/openjournals/joss-reviews/issues/6899

**Comment by VincentAuriau** [comment]
- I have added '''The package introduces the *FeaturesStorage* object''' which makes clearer that it's not from NumPy
- I changed second-order to quasi-Newton
- I removed the paragraph while keeping a word about this streamlined objective in the introduction. It has taken some discussions and time to finally reach the current version that's why I like having a word about it. What do you think about the current version ?

Thank you for your recommendations that help improving the paper !
